zepben/ewb-sdk-jvm

src/main/java/com/zepben/cimbend/grpc/GrpcResult.kt, src/test/kotlin/com/zepben/cimbend/get/testdata/NetworkHierarchyAllTypes.kt
=> EVO-784 - Cleanup for comments left on EVO-706.

src/main/java/com/zepben/cimbend/grpc/ConnectionConfig.kt, src/main/java/com/zepben/cimbend/grpc/GrpcChannelFactory.kt, src/test/kotlin/com/zepben/cimbend/put/grpc/GrpcChannelFactoryTest.kt
EVO-786 - Rationalised gRPC client connection configuration members. Updated javadoc.
=> EVO-786 - Rationalised gRPC client connection configuration members

src/main/java/com/zepben/cimbend/get/CimConsumerClient.kt, src/main/java/com/zepben/cimbend/get/NetworkConsumerClient.kt, src/main/java/com/zepben/cimbend/get/hierarchy/NetworkHierarchy.kt, src/main/java/com/zepben/cimbend/get/hierarchy/NetworkHierarchyFeeder.kt, src/main/java/com/zepben/cimbend/get/hierarchy/NetworkHierarchyGeographicalRegion.kt, src/main/java/com/zepben/cimbend/get/hierarchy/NetworkHierarchyIdentifiedObject.kt, src/main/java/com/zepben/cimbend/get/hierarchy/NetworkHierarchySubGeographicalRegion.kt, src/main/java/com/zepben/cimbend/get/hierarchy/NetworkHierarchySubstation.kt, src/main/java/com/zepben/cimbend/grpc/GrpcClient.kt, src/main/java/com/zepben/cimbend/grpc/GrpcResult.kt, src/test/kotlin/com/zepben/cimbend/get/CimConsumerClientTest.kt, src/test/kotlin/com/zepben/cimbend/get/NetworkConsumerClientTest.kt, src/test/kotlin/com/zepben/cimbend/get/testdata/FeederNetwork.kt, src/test/kotlin/com/zepben/cimbend/get/testdata/NetworkHierarchyAllTypes.kt, src/test/kotlin/com/zepben/cimbend/grpc/GrpcResultTest.kt
=> EVO-790 - Updated licence headers

.idea/codeStyles/codeStyleConfig.xml, docs/release.md, pom.xml, src/main/java/com/zepben/cimbend/get/CustomerConsumerClient.kt, src/main/java/com/zepben/cimbend/get/DiagramConsumerClient.kt, src/main/java/com/zepben/cimbend/grpc/GrpcClient.kt, src/main/java/com/zepben/cimbend/grpc/RpcErrorHandler.kt, src/test/kotlin/com/zepben/cimbend/get/ConsumerUtils.kt, src/test/kotlin/com/zepben/cimbend/get/CustomerConsumerClientTest.kt, src/test/kotlin/com/zepben/cimbend/get/DiagramConsumerClientTest.kt, src/test/kotlin/com/zepben/cimbend/get/NetworkConsumerClientTest.kt, src/test/kotlin/com/zepben/cimbend/grpc/CaptureLastRpcErrorHandler.kt
=> EVO-722 - Added `customer` and `diagram` consumer clients.

docs/release.md, src/main/java/com/zepben/cimbend/cim/iec61970/base/wires/PowerTransformer.kt, src/test/java/com/zepben/cimbend/cim/iec61970/base/wires/PowerTransformerTest.kt
Signed-off-by: Roberto Marquez <roberto.marquez@zepben.com>
=> [EP-143] Added primaryVoltage property to PowerTransformer.

README.md, docs/release.md, pom.xml, src/main/java/com/zepben/cimbend/cim/iec61970/base/wires/PowerTransformer.kt, src/main/java/com/zepben/cimbend/database/sqlite/readers/NetworkCIMReader.kt, src/main/java/com/zepben/cimbend/database/sqlite/tables/TableVersion.kt, src/main/java/com/zepben/cimbend/database/sqlite/tables/iec61970/base/wires/TablePowerTransformers.kt, src/main/java/com/zepben/cimbend/database/sqlite/upgrade/ChangeSet23.kt, src/main/java/com/zepben/cimbend/database/sqlite/upgrade/UpgradeRunner.kt, src/main/java/com/zepben/cimbend/database/sqlite/writers/NetworkCIMWriter.kt, src/main/java/com/zepben/cimbend/network/NetworkServiceComparator.kt, src/main/java/com/zepben/cimbend/network/model/NetworkCimToProto.kt, src/main/java/com/zepben/cimbend/network/model/NetworkProtoToCim.kt, src/test/java/com/zepben/cimbend/cim/iec61970/base/wires/PowerTransformerTest.kt, src/test/java/com/zepben/cimbend/database/sqlite/DatabaseSqliteTest.kt, src/test/java/com/zepben/cimbend/network/FillFields.kt, src/test/java/com/zepben/cimbend/network/NetworkServiceComparatorTest.kt, src/test/java/com/zepben/cimbend/network/model/NetworkCimToProtoTest.kt, src/test/java/com/zepben/cimbend/network/model/NetworkCimToProtoTestValidator.kt, src/test/java/com/zepben/cimbend/network/model/NetworkProtoToCimTest.kt, src/test/java/com/zepben/cimbend/network/model/NetworkProtoToCimTestValidator.kt, src/test/java/com/zepben/cimbend/testdata/SchemaTestNetwork.kt
Signed-off-by: Roberto Marquez Vasquez <roberto.marquez@zepben.com>
=> * Added transformer utilisation property to PowerTransformer class.

src/main/java/com/zepben/cimbend/network/model/NetworkCimToProto.kt, src/test/java/com/zepben/cimbend/network/FillFields.kt, src/test/java/com/zepben/cimbend/network/model/NetworkCimToProtoTest.kt, src/test/java/com/zepben/cimbend/network/model/NetworkCimToProtoTestValidator.kt
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>
=> Clear correct fields when serialising TransformerEnd to protobuf

docs/babel.config.js, docs/docs/consumer.mdx, docs/docs/datamodel.mdx, docs/docs/services.mdx, docs/docs/tracing.mdx, docs/docusaurus.config.js, docs/sidebars.js, docs/src/theme/SearchBar/index.js
Fixed typos, changed links to docusaurus
=> SITE-50_Read-the-documentation-and-identify-typos-and-bugs

docs/package-lock.json, docs/package.json
Signed-off-by: Varun Ramani <varun.ramani@zepben.com>
=> Upgrade doc deps

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json, docs/src/pages/index.tsx
Signed-off-by: Varun Ramani <varun.ramani@zepben.com>
=> Upgrade docusaurus preset

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json
Signed-off-by: Varun Ramani <varun.ramani@zepben.com>
=> Upgrade preset and pull in default algolia config

src/main/java/com/zepben/evolve/cim/iec61970/base/diagramlayout/DiagramObjectStyle.kt
Added diagram object styles for power electronics connection and units
=> PROJ-241_Add-layer-to-map-to-show-DER

src/main/java/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt
Signed-off-by: Glenn Carwardine <glenn.carwardine@zepben.com>
=> Added missing BUSBARSECTION handling in network consumer client.

docs/docs/consumer.mdx, docs/docs/datamodel.mdx, docs/versioned_docs/version-0.4.0/datamodel.mdx, docs/versioned_docs/version-0.4.0/persistence.mdx, docs/versioned_docs/version-0.5.0/datamodel.mdx, docs/versioned_docs/version-0.5.0/persistence.mdx
Signed-off-by: ryanjcoleman <ryan.coleman@zepben.com>
=> Fixed links to tracing, added changes to prev versions

README.md, docs/docs/datamodel.mdx, docs/versioned_docs/version-0.4.0/datamodel.mdx, docs/versioned_docs/version-0.5.0/datamodel.mdx
Signed-off-by: ryanjcoleman <ryan.coleman@zepben.com>
=> Fixed readme links, updated links to Discussions

README.md, changelog.md, src/main/java/com/zepben/evolve/database/sqlite/DatabaseTables.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/DatabaseTablesTest.kt
Signed-off-by: Glenn Carwardine <glenn.carwardine@zepben.com>
=> DatabaseTables no longer use reflection so run faster.

src/main/java/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet29.kt
=> Fixed error in created table in v29 upgrade scripts

changelog.md, docs/docs/consumer.mdx, pom.xml, src/main/java/com/zepben/evolve/streaming/get/CustomerConsumerClient.kt, src/main/java/com/zepben/evolve/streaming/get/DiagramConsumerClient.kt, src/main/java/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt, src/main/java/com/zepben/evolve/streaming/grpc/AuthType.kt, src/main/java/com/zepben/evolve/streaming/grpc/EvolveCallCredentials.kt, src/main/java/com/zepben/evolve/streaming/grpc/JwtCredentials.kt, src/main/java/com/zepben/evolve/streaming/put/CustomerProducerClient.kt, src/main/java/com/zepben/evolve/streaming/put/DiagramProducerClient.kt, src/main/java/com/zepben/evolve/streaming/put/NetworkProducerClient.kt, src/test/kotlin/com/zepben/evolve/streaming/grpc/JwtCredentialsTest.kt
Went with kotlinx.serialisation for JSON serialisation which requires kotlin 1.4.30, so had to update the super pom. People will need to update their IDEs.
this also introduces kotlin-wiremock as a test dependency. If this PR gets accepted I will add these deps to the super pom and update this pom before merge.
=> Ewb 658 implement oauth for g rpc in jvm sdk

changelog.md, src/main/kotlin/com/zepben/evolve/services/network/tracing/ConnectedEquipmentTrace.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/Tracing.kt, src/test/kotlin/com/zepben/evolve/services/network/testdata/ConnectedEquipmentNetwork.kt, src/test/kotlin/com/zepben/evolve/services/network/testdata/TestDataCreators.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/ConnectedEquipmentTraceTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/TracingTest.kt
=> Added normal and current version of the connected equipment trace

README.md
=> Added codecov badge to README

.github/workflows/maven-lib-build.yml
=> EWB-739 - Added codecov report upload to the build action

src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet31.kt
Removed erroneous empty list from the v31 change set and fixed syntax errors now the actual upgrade is being run.
Signed-off-by: Anthony Charlton <anthony.charlton@zepben.com>1
=> Fixed v31 changeset

changelog.md, src/main/kotlin/com/zepben/evolve/services/common/BaseServiceComparator.kt, src/main/kotlin/com/zepben/evolve/services/common/ServiceDifferences.kt, src/test/kotlin/com/zepben/evolve/services/common/ServiceDifferencesTest.kt
=> EWB-847 - Corrected string conversion of `ServiceDifferences` with `NameType` differences.

changelog.md, docs/src/pages/release-notes.md, pom.xml, src/main/kotlin/com/zepben/evolve/cim/iec61968/metering/UsagePoint.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/readers/NetworkCIMReader.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableVersion.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61968/metering/TableUsagePoints.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/UpgradeRunner.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet35.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/writers/NetworkCIMWriter.kt, src/main/kotlin/com/zepben/evolve/services/network/NetworkServiceComparator.kt, src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkCimToProto.kt, src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkProtoToCim.kt, src/test/kotlin/com/zepben/evolve/cim/iec61968/metering/UsagePointTest.kt, src/test/kotlin/com/zepben/evolve/services/network/NetworkServiceComparatorTest.kt, src/test/kotlin/com/zepben/evolve/services/network/testdata/FillFields.kt
=> EWB-836 - Added `isVirtual` and `connectionCategory` to `UsagePoint`

src/main/kotlin/com/zepben/evolve/cim/iec61968/assetinfo/TransformerEndInfo.kt, src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/PowerTransformerEnd.kt, src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/TransformerStarImpedance.kt, src/main/kotlin/com/zepben/evolve/services/network/ResistanceReactance.kt, src/test/kotlin/com/zepben/evolve/cim/iec61968/assetinfo/TransformerEndInfoTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/PowerTransformerEndTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/TransformerStarImpedanceTest.kt, src/test/kotlin/com/zepben/evolve/services/network/ResistanceReactanceTest.kt
=> EWB-772 - Calculating resistance/reactance from end info tests.

changelog.md, src/main/kotlin/com/zepben/evolve/database/sqlite/DatabaseReader.kt, src/main/kotlin/com/zepben/evolve/services/network/NetworkService.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/Tracing.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityResult.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityTrace.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityTracker.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseTrace.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/RemovePhases.kt, src/test/kotlin/com/zepben/evolve/services/network/NetworkServiceTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityResultTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityTraceTest.kt
=> Created new traces for tracing connectivity using `ConnectivityResult`.

src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityTrace.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityTraceTest.kt
=> Fixed bug with connectivity trace with multiple things connected to the same terminal.

src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityTrace.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectivityTraceTest.kt
=> Changed connectivity trace processing of busbars to allow stop conditions to match a busbar

pom.xml, src/test/kotlin/com/zepben/evolve/cim/iec61968/assetinfo/PowerTransformerInfoTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61968/assetinfo/TransformerEndInfoTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61968/assetinfo/TransformerTankInfoTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/PowerTransformerEndTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/TransformerStarImpedanceTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseStepTest.kt, src/test/kotlin/com/zepben/evolve/streaming/get/AwaitableStreamObserverTest.kt, src/test/kotlin/com/zepben/evolve/streaming/get/CustomerConsumerClientTest.kt, src/test/kotlin/com/zepben/evolve/streaming/get/DiagramConsumerClientTest.kt, src/test/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClientTest.kt
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>
=> Update to latest superpom

src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/ShuntCompensator.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/readers/NetworkCIMReader.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableVersion.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61970/base/wires/TableShuntCompensators.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/UpgradeRunner.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet37.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/writers/NetworkCIMWriter.kt, src/main/kotlin/com/zepben/evolve/services/common/ReferenceResolvers.kt, src/main/kotlin/com/zepben/evolve/services/common/Resolvers.kt, src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkPbExtensions.kt, src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkProtoToCim.kt, src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/ShuntCompensatorTest.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/ChangeSetTest.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet22Validator.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet23Validator.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet35Validator.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet37Validator.kt, src/test/kotlin/com/zepben/evolve/services/network/testdata/FillFields.kt
=> EWB-999 - Allowed linking between shunt compensator and asset info.

src/main/kotlin/com/zepben/evolve/services/network/tracing/FindWithUsagePoints.kt, src/test/kotlin/com/zepben/evolve/services/network/testdata/WithUsagePointsNetwork.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/FindWithUsagePointsTest.kt
=> PROJ-1550 - Updated usage point trace to detect non-virtual LV aggregation usage points.

src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableVersion.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61970/base/core/TableBaseVoltages.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61970/base/scada/TableRemoteControls.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61970/base/scada/TableRemoteSources.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/UpgradeRunner.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet38.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/ChangeSetTest.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet38Validator.kt
Signed-off-by: Jimmy Tung <jimmy.tung@zepben.com>
=> Fix incorrectly named database columns

src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet38Validator.kt
=> Updated change-set 38 validation to insert into table before modification and validate all expected indexes.

pom.xml, src/main/kotlin/com/zepben/evolve/cim/iec61970/base/core/PhaseCode.kt, src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/SinglePhaseKind.kt, src/test/kotlin/com/zepben/evolve/cim/iec61970/base/core/PhaseCodeTest.kt
Signed-off-by: Jimmy Tung <jimmy.tung@zepben.com>
=> added phase code ,single phase kind and update pom

changelog.md, pom.xml, src/main/kotlin/com/zepben/evolve/cim/iec61968/infiec61868/infassetinfo/TransformerConstructionKind.kt, src/main/kotlin/com/zepben/evolve/cim/iec61968/infiec61868/infassetinfo/TransformerFunctionKind.kt, src/main/kotlin/com/zepben/evolve/cim/iec61968/infiec61968/infassetinfo/TransformerConstructionKind.kt, src/main/kotlin/com/zepben/evolve/cim/iec61968/infiec61968/infassetinfo/TransformerFunctionKind.kt, src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/PowerTransformer.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/readers/NetworkCIMReader.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableVersion.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61970/base/wires/TablePowerTransformers.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/UpgradeRunner.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet24.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet38.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet39.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/writers/NetworkCIMWriter.kt, src/main/kotlin/com/zepben/evolve/services/network/NetworkServiceComparator.kt, src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkCimToProto.kt, src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkProtoToCim.kt, src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/PowerTransformerTest.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/ChangeSetTest.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet20Validator.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet33Validator.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet34Validator.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet38Validator.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet39Validator.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSetValidator.kt, src/test/kotlin/com/zepben/evolve/services/network/NetworkServiceComparatorTest.kt, src/test/kotlin/com/zepben/evolve/services/network/testdata/FillFields.kt
=> EWB-774 - Added fields to `PowerTransformer` to define `constructionKind` and `function`.

changelog.md, pom.xml, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableVersion.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61970/base/wires/TablePowerElectronicsConnectionPhases.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61970/base/wires/generation/production/TablePowerElectronicsUnit.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/UpgradeRunner.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet40.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/ChangeSetTest.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet40Validator.kt
Signed-off-by: Jimmy Tung <jimmy.tung@zepben.com>
=> Fix power electronic connection mrid indexing on multiple tables

changelog.md, pom.xml, src/main/kotlin/com/zepben/evolve/cim/iec61968/common/StreetAddress.kt, src/main/kotlin/com/zepben/evolve/cim/iec61968/common/StreetDetail.kt, src/main/kotlin/com/zepben/evolve/cim/iec61968/common/TownDetail.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/readers/NetworkCIMReader.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableVersion.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61968/common/TableStreetAddresses.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61968/common/TableTownDetails.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/UpgradeRunner.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet41.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/writers/NetworkCIMWriter.kt, src/main/kotlin/com/zepben/evolve/services/common/extensions/StringExtensions.kt, src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkCimToProto.kt, src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkProtoToCim.kt, src/test/kotlin/com/zepben/evolve/cim/iec61968/common/LocationTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61968/common/StreetAddressTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61968/common/StreetDetailTest.kt, src/test/kotlin/com/zepben/evolve/cim/iec61968/common/TownDetailTest.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/ChangeSetTest.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet41Validator.kt, src/test/kotlin/com/zepben/evolve/services/network/NetworkModelTestUtil.kt, src/test/kotlin/com/zepben/evolve/services/network/NetworkServiceComparatorTest.kt, src/test/kotlin/com/zepben/evolve/services/network/testdata/FillFields.kt, src/test/kotlin/com/zepben/evolve/services/network/testdata/StupidlyLargeNetwork.kt
=> Update StreetAddress and usages

pom.xml
=> Specify kotlin version 1.5 in pom

src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/RemoveDirection.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirection.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseTrace.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/RemovePhases.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/SetPhases.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/tree/DownstreamTree.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirectionTest.kt
=> PROJ-2227 - Removed checking of phase paths from the direction setting algorithms.

src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirection.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/DatabaseSqliteTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirectionTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/tree/DownstreamTreeTest.kt
=> PROJ-2257 - Stopped SetDirection from reprocessing loops in an attempt to apply edge case BOTH status

src/main/kotlin/com/zepben/evolve/testing/TestNetworkBuilder.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/RemoveDirectionTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirectionTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseInferrerTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/RemovePhasesTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/SetPhasesTest.kt, src/test/kotlin/com/zepben/evolve/testing/TestNetworkBuilderTest.kt
=> PROJ-2264 - Updated `TestNetworkBuilder` to support transformers and generic conducting equipment

src/main/kotlin/com/zepben/evolve/services/network/tracing/Tracing.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/TracingTest.kt
=> Added `removeDirection` helper to `Tracing`

changelog.md, src/main/kotlin/com/zepben/evolve/services/network/NetworkService.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TerminalConnectivityConnected.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TerminalConnectivityInternal.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TransformerPhasePaths.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/SetPhases.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/DatabaseSqliteTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TerminalConnectivityConnectedTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/SetPhasesTest.kt
=> PROJ-2342 - Phases are now set through transformers.

changelog.md, src/main/kotlin/com/zepben/evolve/cim/iec61970/base/core/Terminal.kt, src/main/kotlin/com/zepben/evolve/services/common/BaseServiceComparator.kt, src/main/kotlin/com/zepben/evolve/services/common/PropertyComparers.kt, src/main/kotlin/com/zepben/evolve/services/diagram/DiagramServiceComparator.kt, src/main/kotlin/com/zepben/evolve/services/measurement/MeasurementServiceComparator.kt, src/main/kotlin/com/zepben/evolve/services/network/NetworkServiceComparator.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseStatus.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/TracedPhases.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseSelectorTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/TracedPhasesTest.kt
=> PROJ-2376 - You can now translate `TracedPhases` to a `PhaseCode` if the individual phases make sense

.gitignore, docs/docs/phases.mdx, docs/sidebars.js, src/main/kotlin/com/zepben/evolve/cim/iec61970/base/core/PhaseCode.kt, src/test/kotlin/com/zepben/evolve/database/sqlite/DatabaseSqliteTest.kt
* Added doco for phase and feeder direction changes
* Added doco for phase and feeder direction changes. Added Java interop `PhaseCode.forEach` due to issues with documenting usage.
=> PROJ-2407 - Added doco for phase and feeder direction changes

changelog.md, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/SetPhases.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/FeederDirectionTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/SetPhasesTest.kt
=> EWB-1457 - `SetPhases` now supports setting backwards through XN/XY transformers.

src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectedEquipmentTrace.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectedEquipmentTraceTest.kt
=> EWB-1777 - Added support for starting connected equipment traces from open points.

src/main/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt
Signed-off-by: Kurt Greaves <kurt.greaves@zepben.com>
=> Fix concurrent modification exception when resolving references

src/main/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt, src/test/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClientTest.kt
Signed-off-by: Roberto Marquez Vasquez <roberto.marquez@zepben.com>
=> Added test to reveal concurrent modification exception when requesting objects with unresolved references, and fixed it.

changelog.md, pom.xml, src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/LimitedConnectedEquipmentTrace.kt, src/main/kotlin/com/zepben/evolve/streaming/get/CimConsumerClient.kt, src/main/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt, src/test/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClientTest.kt
=> EWB-1797: Support linked container options in getEquipmentForContainers

changelog.md, src/main/kotlin/com/zepben/evolve/services/network/tracing/FindSwerEquipment.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/FindSwerEquipmentTest.kt
=> EWB-1841 - Added trace for finding SWER equipment on networks or feeders.

src/main/kotlin/com/zepben/evolve/services/network/tracing/FindSwerEquipment.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/FindSwerEquipmentTest.kt
=> EWB-1843 - Reset trace before use in `FindSwerEquipment`

src/main/kotlin/com/zepben/evolve/services/network/tracing/FindSwerEquipment.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/FindSwerEquipmentTest.kt
=> EWB-1844: Fixed a bug in the `FindSwerEquipment` trace that allowed tracing via looped SWER LV onto non SWER network.

pom.xml
Update evolve-grpc to version using same version of super pom. No changes are introduced in this other than the super pom update.
=> Use latest evolve-grpc

changelog.md
Signed-off-by: Alex Lourie <alex.lourie@zepben.com>
=> Fixing version format to match the one expected by CI

changelog.md, src/main/kotlin/com/zepben/evolve/services/network/NetworkService.kt, src/test/kotlin/com/zepben/evolve/services/customer/CustomerServiceTest.kt, src/test/kotlin/com/zepben/evolve/services/diagram/DiagramServiceTest.kt, src/test/kotlin/com/zepben/evolve/services/network/NetworkServiceTest.kt
Signed-off-by: Jimmy Tung <jimmy.tung@zepben.com>
fix remove lvfeeder
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
=> fix remove lvfeeder

changelog.md, pom.xml
Dep update with no changes needed - fixes HC loadshape byte ordering issue.
=> Update to latest evolve-grpc

changelog.md, pom.xml, src/main/kotlin/com/zepben/evolve/streaming/grpc/Connect.kt, src/test/kotlin/com/zepben/evolve/streaming/grpc/ConnectTest.kt
Small update to properly call require createTokenFetcher calls.
=> Azure auth support

changelog.md, pom.xml
Updated super pom version.
Updated version of evolve-grpc library.
Updated super pom version and evolve-grpc library version to support functionality needed in hosting capacity service.
PRs needed to be merged before this:
https://github.com/zepben/evolve-grpc/pull/78
Tasks:
PROJ-3807
PROJ-3770
~~- [ ] I have performed a self review of my own code (including checking issues raised when creating the PR).~~
~~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~~
~~- [ ] I have commented my code in any hard-to-understand or hacky areas.~~
~~- [ ] I have updated any documentation required for these changes.~~
=> Updated super pom version and evolve-grpc library version to support functionality needed in hosting capacity service.

pom.xml, src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/Switch.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/TracedPhasesBitManipulation.kt, src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/ConductorTest.kt
Updated to latest super pom with Kotlin 1.9.10. 
https://github.com/zepben/evolve-super-pom/pull/33
=> EWB-2879: Update super pom/Kotlin version

changelog.md, docs/docs/consumer.mdx, pom.xml, src/main/kotlin/com/zepben/evolve/database/sqlite/DatabaseReader.kt, src/main/kotlin/com/zepben/evolve/streaming/grpc/Connect.kt, src/test/kotlin/com/zepben/evolve/streaming/grpc/ConnectTest.kt
Provide a helper function for creating a GRPC channel by fetching an Auth token using a managed identity URL on Azure. 
=> Implement the managed identity token fetcher for Azure

changelog.md, pom.xml
Updated grpc version.
EWB-4077
~~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~~
~~- [ ] I have commented my code in any hard-to-understand or hacky areas.~~
~~- [ ] I have updated any documentation required for these changes.~~
=> Updated grpc version.

pom.xml, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/Column.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableMetadataDataSources.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableVersion.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/NominalPhasePath.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseStep.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseStepTracker.kt, src/test/java/com/zepben/evolve/services/network/tracing/traversals/BranchRecursiveTraversalJavaTest.java
Updated Zepben dependencies for new super-pom.
Already covered by previous PR's
=> EWB-4230: Updated Zepben dependencies for new super-pom.

changelog.md, pom.xml
Update evolve-conn to fix bug and make issuer issuerDomain again.
Also fixes saving of JWKs after they are refreshed - both changes applicable only to EWB.
Please leave a summary of the breaking changes here. This is useful for the reviewer, but also is useful for communication to the team when merged (e.g. you could copy and paste the summary into slack).
=> Update evolve conn to fix issuer key in auth configuration route

changelog.md, docs/docs/overview.md, docs/sidebars.js
Adds feature list to doco.
No blocking nor blocked tasks.
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ (No tests needed for doco change)
No breaking changes.
| Before | After |
| --- | --- |
| (no feature list) | ![image](https://github.com/zepben/ewb-sdk-jvm/assets/19983470/90d8d049-792c-42c1-b4e3-1f5931cc5438) |
=> DEV-540: Add feature list

changelog.md, src/main/kotlin/com/zepben/evolve/database/paths/EwbDataFilePaths.kt, src/main/kotlin/com/zepben/evolve/database/paths/LocalEwbDataFilePaths.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/tables/iec61970/base/wires/TableRotatingMachines.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/tables/iec61970/base/wires/TableSynchronousMachines.kt, src/test/kotlin/com/zepben/evolve/database/paths/LocalEwbDataFilePathsTest.kt
Refactored EwbDataFilePaths: The EwbDataFilePaths class has been refactored into an interface to enhance flexibility and abstraction. A new class, LocalEwbDataFilePaths, has been introduced to specifically handle the resolution of database paths for the local file system. This change improves the maintainability and extensibility of the codebase by decoupling the path management logic from the implementation details.
No associated tasks. Consumers will be updated as needed.
Test can be achieved by using the new `LocalEwbDataFilePaths` class to resolve database file paths.
Files changed does not have any documentation.
API usage has breaking …
=> Dev 1355 update sdk ewb data file paths to use an interface

changelog.md, pom.xml
Pom update for proto passthrough
None relevant to SDK
=> [DEV-1489] Include failure opendss report type.

pom.xml
Just bumping evolve-conn for a pass through dependency for EWB. Explicitly did not put anything in the changelog since it doesn't affect anything in this project.
- Requires https://github.com/zepben/ewb-conn-jvm/pull/22
N/A
=> [DEV-1786] Bump Evolve Conn for JWKS Cert Verification Feature

pom.xml, src/main/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateClient.kt, src/main/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateService.kt, src/test/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateServiceTest.kt, src/test/kotlin/com/zepben/evolve/streaming/get/testservices/TestQueryNetworkStateService.kt
Updated to use gRPC library with renamed network state fields.
~- [ ] I have updated the changelog.~ Change to a new feature that is already covered
=> Updated to use gRPC library with renamed network state fields.

pom.xml
Just bumping dependencies, noop change to this repo. No changelog required.
- https://github.com/zepben/ewb-conn-jvm/pull/23
N/A
=> [DEV-1821] Bump evolve-conn with Vertx Cert verify - NOOP

pom.xml
Just updating super-pom. Full story can be found here https://github.com/zepben/ewb-super-pom/pull/54/files. Explicitly not updating the changelog as these changes have no direct effect to this repo
Green build means go. 
- [] ~I have updated the changelog.~ Explicitly not doing it as these changes have no direct effect to this repo
=> [DEV-2185] Update Super Pom to 0.37.0 and Evolve Conn to 0.21.0-SNAPSHOT3

src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToLvFeeders.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToLvFeedersTest.kt
Updated the LV feeder energisation to include current (was only doing normal before)
None.
~- [ ] I have updated the changelog.~ Already covered by existing entry
Non-breaking
=> [DEV2254] Updated the LV feeder energisation to include current

docs/docs/datamodel.mdx
remove slug
A summary of the changes and what they achieve. If there is a ClickUp task with decent detail associated with this change the summary can be brief, otherwise please add some motivation and context here.
If you have added new dependencies to the project please state why.
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
If any of these are not applicable, strikethrough the line `~like this~`. **Do not …
=> Remove slug from datamodel.mdx

changelog.md, docs/docs/query-network-state-client.mdx, docs/docs/query-network-state-service.mdx, src/main/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateClient.kt, src/test/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateClientTest.kt, src/test/kotlin/com/zepben/evolve/streaming/get/testservices/TestQueryNetworkStateService.kt
Added the client side implementation of the `reportBatchStatus` gRPC message.
If you want more than what the unit tests provide, you just need to connect the client to a server and make sure you can send the statuses.
Non-breaking.
=> Dev 2415 add report batch status support

changelog.md, src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirection.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTrace.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceExtensions.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceQueueNext.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceStepPathProvider.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/Conditions.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/DirectionCondition.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/operators/ConnectivityStateOperators.kt, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/operators/NetworkStateOperators.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceQueueNextTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceStepPathProviderTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/ConditionsTest.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/DirectionConditionTest.kt
Fixes direction setting and tracing of networks with cuts and clamps.
This is required to finish https://app.clickup.com/t/6929263/DEV-2007
Run the unit tests.
- ~[ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~ Some unit tests were added but we are going to add more thorough tests in another pass so we can get this in.
- ~[ ] I have updated any documentation required for these changes.~
Please leave a summary of the breaking changes here. This is useful for the reviewer, but also is useful for communication to the team when merged (e.g. you could copy and paste the summary into …
=> DEV-2506 Cuts and clamps direction fixes

src/main/kotlin/com/zepben/evolve/testing/TestNetworkBuilder.kt
Added the action blocks that were missed on initial implementation.
- https://github.com/zepben/ewb-sdk-jvm/pull/221
None.
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
~- [ ] I have updated the changelog.~
Non-breaking
=> [DEV-2574] Added action blocks for `TestNetworkBuild.withClamp` and `TestNetworkBuild.withCut`

changelog.md, src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceStepPathProvider.kt, src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceStepPathProviderTest.kt
Bug fix - sat with Anthony we know what's going on...
=> [DEV-2592] Fixed a bug when traversing AcLineSegments with a single cut or clamp.

changelog.md, src/main/kotlin/com/zepben/evolve/database/sql/BaseEntryWriter.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/CimWriter.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/customer/CustomerCimWriter.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/customer/CustomerDatabaseTables.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/diagram/DiagramCimWriter.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/diagram/DiagramDatabaseTables.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkCimWriter.kt, src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkDatabaseTables.kt
Expose the writers
- https://github.com/zepben/load-processing-common/pull/6
- https://github.com/zepben/load-aggregator/pull/9
visibility modifier update only
None
=> [DEV-2860] Expose database writers 

changelog.md, src/main/kotlin/com/zepben/ewb/issues/IssueTracker.kt, src/main/kotlin/com/zepben/ewb/issues/IssueTrackerGroup.kt, src/main/kotlin/com/zepben/ewb/issues/IssuesLog.kt, src/main/kotlin/com/zepben/ewb/issues/TestExtensions.kt, src/main/kotlin/com/zepben/ewb/metrics/NetworkContainer.kt, src/main/kotlin/com/zepben/ewb/streaming/get/NetworkStateIssues.kt, src/main/kotlin/com/zepben/ewb/streaming/get/QueryNetworkStateClient.kt, src/main/kotlin/com/zepben/ewb/streaming/get/QueryNetworkStateService.kt, src/test/kotlin/com/zepben/ewb/auth/server/grpc/AuthInterceptorTest.kt, src/test/kotlin/com/zepben/ewb/issues/IssueTrackerGroupTest.kt, src/test/kotlin/com/zepben/ewb/issues/IssueTrackerTest.kt, src/test/kotlin/com/zepben/ewb/issues/IssuesLogTest.kt, src/test/kotlin/com/zepben/ewb/streaming/get/QueryNetworkStateClientTest.kt, src/test/kotlin/com/zepben/ewb/streaming/get/QueryNetworkStateServiceTest.kt
A few fixes for current state APIs, and also moving the IssueTracker libraries from the migrator-sdk
None
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
It's currently running in production.
When developing applications, use following guidelines for information security considerations:
* Access to applications should be protected with security keys/tokens or usernames and passwords;
* All sessions are encrypted if possible;
* All application input is sanitised before being acted on (ie SQL statements, etc);
* Log messages, and especially client-facing ones, …
=> [DEV-3267] Move IssueTracker to SDK
