- changelog.md
- src/main/kotlin/com/zepben/evolve/streaming/get/CimConsumerClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/CustomerConsumerClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/DiagramConsumerClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/grpc/GrpcResult.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/CustomerConsumerClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/DiagramConsumerClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/grpc/GrpcResultTest.kt
* `getIdentifiedObject` now returns a `NoSuchElementException` error if the requested object does not exist rather than a `null` successful result.
* `getIdentifiedObjects` now adds unknown mRIDs to the failed collection.
* Fixed an error in the typing for `GrpcResult` that allowed you to set a value to `null` without specifying a nullable type.
> Ewb 739 grpc result nullability

- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/PowerTransformer.kt
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/TransformerEnd.kt
When we get this sounding accurate/reasonable I'll make the addition to the python SDK as well.
Sorry about the noise, had to fix formatting so that the []'s actually worked properly in the IDE. Basically you're only looking at the last block of text in each comment (starImpedance and assetInfo)
> Add clarification for restrictions on starImpedance and assetInfo for transformers

- src/main/kotlin/com/zepben/evolve/services/common/BaseService.kt
- src/test/kotlin/com/zepben/evolve/services/common/BaseServiceTest.kt
I think this behaviour makes more sense (it's even in line with the function docs) - basically if you add something that is already in the service you still get back a return of true. That way if people add the same thing multiple times they can still rely on add to tell them if it's in the service.
I'm doubtful that anyone is relying on the existing behaviour so I think it'd be safe to merge.
> Return true if object already in service

- changelog.md
- src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirection.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirectionTest.kt
> PROJ-2313 - `SetDirection` now correctly handles `Switch` instances without phases.

- changelog.md
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/core/Terminal.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61970/base/core/TerminalTest.kt
* Added `connectedTerminals` and `otherTerminals` helper methods to `Terminal`
* Made `Terminal` methods `connect` and `disconnect` internal.
> `Terminal` helpers

- changelog.md
- src/main/kotlin/com/zepben/evolve/testing/TestNetworkBuilder.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/RemoveDirectionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirectionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseInferrerTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/RemovePhasesTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/SetPhasesTest.kt
- src/test/kotlin/com/zepben/evolve/testing/TestNetworkBuilderTest.kt
* Changed `TestNetworkBuilder` to have a public constructor and removed `startWith*` functions. Change `TestNetworkBuilder.startWith*` to `TestNetworkBuilder().from*` _(kotlin)_, or `new TestNetworkBuilder().from*` _(java)_.
* Changed `TestNetworkBuilder.fromOther` and `TestNetworkBuilder.toOther` to take a creator, rather than an instance.
> Changed `TestNetworkBuilder` to handle 'other' better, and not be statically constructed.

- changelog.md
- src/main/kotlin/com/zepben/evolve/services/network/tracing/tree/TreeNode.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/tree/TreeNodeTest.kt
> EWB-1622: Make sortWeight return 1 for equipment without terminals

- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssociatedTerminalTrackerTest.kt
> EWB-1560: Port tests for associated terminal tracker from python sdk

- changelog.md
- src/main/kotlin/com/zepben/evolve/database/sqlite/DatabaseReader.kt
The kotlin `and` statement doesn't cause a short circuit (wtf) which means we apply phases and direction before we eventually fail, which can be time consuming. This looks like it's possibly quite old from when we converted to kotlin (change is beyond when we squashed history), so I don't think it's intentional as the logs you get from the postLoad steps hide the real causes of failure.
For reference:
```kotlin
/**
* Performs a logical `and` operation between this Boolean and the [other] one. Unlike the `&&` operator,
* this function does not perform short-circuit evaluation. Both `this` and [other] will always be evaluated.
*/
public infix fun and(other: Boolean): Boolean
```
> Don't apply phases/set direction if loading the database fails

- changelog.md
- src/main/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClientTest.kt
The functions that wrap `getEquipmentForContainers`, named `getEquipmentContainer(s)`, provide more helpful HTTP error codes and reponses. This PR adds the same functionality that was added in https://github.com/zepben/evolve-sdk-jvm/pull/110 for these functions.
- This task blocks https://github.com/zepben/feeder-load-analysis/pull/3 from merging.
> EWB-1854: Add linked container parameters for getEquipmentContainer(s)

- pom.xml
Signed-off-by: Roberto Marquez Vasquez <roberto.marquez@zepben.com>
This is only a super-pom version update. The reason for the update is other repos are pointing to a newer super-pom than the sdk and super-pom version differences is causing issues with grpc. This update basically fixes the issue by putting all version in sync.
EWB-1885
EWB-1886
EWB-1887
EWB-1888
RE: This is just a pom-version update, no tests broke after the update and no additional tests are needed.
> Updated super-pom version

- changelog.md
- src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TransformerPhasePaths.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TerminalConnectivityInternalTest.kt
Adding support when setting phases for YYN single phase transformers. This isn't complete and still needs tests, and needs to be run over other networks. It works for endeavours network, however I haven't yet checked if it breaks other networks.
> Ewb 1930 support yyn tx

- changelog.md
- src/main/kotlin/com/zepben/evolve/cim/iec61968/assetinfo/TransformerEndInfo.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61968/assetinfo/TransformerEndInfoTest.kt
`calculateRXFromTest` was not using the correct formulas to calculate impedance from a short circuit test. This PR fixes it.
See https://en.wikipedia.org/wiki/Short-circuit_test for the formulas used.
No blocking or blocked tasks.
> EWB-1354: Fix impedance calculation from short circuit test

- changelog.md
- src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/LimitedConnectedEquipmentTrace.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/LimitedConnectedEquipmentTraceTest.kt
Fixes bug where running a directed limited connected trace with `maximumSteps = 1` could return equipment 2 steps away. See https://app.clickup.com/t/6929263/EWB-2538 for more detailed explanation.
- None
- None
Tasks mirroring this one:
- Same bug fix in Python SDK: https://github.com/zepben/evolve-sdk-python/pull/116
> EWB-2538: Fix limited connected trace

- changelog.md
- src/main/kotlin/com/zepben/evolve/database/sqlite/tables/TableVersion.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/tables/iec61970/base/auxiliaryequipment/TablePotentialTransformers.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/UpgradeRunner.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet46.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/ChangeSetTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/upgrade/changesets/ChangeSet46Validator.kt
Fixes column to be non-null, aligning it with the CIM model.
- None
- None
> EWB-3138: Fix column nullability

- changelog.md
- src/main/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/TestDataCreators.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/testdata/LvFeedersWithOpenPoint.kt
- src/test/kotlin/com/zepben/evolve/streaming/grpc/GrpcClientTest.kt
This stops open points between LvFeeders pulling in other LvFeeders and their equipment
> Don't resolve EquipmentContainers when resolving references.

- changelog.md
- src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectedEquipmentTrace.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/ConnectedEquipmentTraceTest.kt
Performance enhancement for `ConnectedEquipmentTrace` when traversing elements with single terminals.
> EWB-3608: Performance enhancement for `ConnectedEquipmentTrace`

- changelog.md
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/core/PhaseCode.kt
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/PowerTransformerEnd.kt
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/SinglePhaseKind.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/DatabaseWriter.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TransformerPhasePaths.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirection.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/traversals/BasicQueue.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/traversals/Traversal.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/traversals/TraversalQueue.kt
- src/main/kotlin/com/zepben/evolve/testing/TestNetworkBuilder.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61970/base/core/PhaseCodeTest.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/SinglePhaseKindTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TerminalConnectivityInternalTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirectionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/traversals/BasicTraversalTest.kt
- src/test/kotlin/com/zepben/evolve/testing/TestNetworkBuilderTest.kt
* Added support for LV2 below SWER transformers.
* Improved logging when saving a database.
* The `TestNetworkBuilder` has been enhanced with the following features:
* You can now set the ID's without having to create a customer 'other' creator.
* Added Kotlin wrappers for `.fromOther` and `.toOther` that allow you to pass a class type rather than a creator.
* Added inbuilt support for `EnergyConsumer`
* The `to*` and `connect` functions can specify the connectivity node mRID to use.
* Added `+` and `-` operators to `PhaseCode` and `SinglePhaseKind`.
* `TraversalQueue` now has `addAll` methods taking either a collection or varargs
* `Traversal` has two new helper methods:
* `ifNotStopping`: Adds a step action that is only called if the traversal is not stopping on the item.
* …
> EWB-3787: LV2 support and trace enhancements

- pom.xml
Bumps version of evolve-grpc to support the added config fields
- https://github.com/zepben/network-verifier-lib/pull/25
- Update opendss-exporter-jvm
> PROJ-3555: Bump version of evolve-grpc

- .idea/codeStyles/Project.xml
- changelog.md
- docs/docs/consumer.mdx
- src/main/kotlin/com/zepben/evolve/services/common/meta/MetadataTranslations.kt
- src/main/kotlin/com/zepben/evolve/services/common/meta/ServiceInfo.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/CimConsumerClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/CustomerConsumerClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/DiagramConsumerClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/grpc/GrpcClient.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/RegulatingCondEqTest.kt
- src/test/kotlin/com/zepben/evolve/services/common/meta/MetadataTranslationsTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/CimConsumerClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/CustomerConsumerClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/DiagramConsumerClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/testservices/TestCustomerConsumerService.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/testservices/TestDiagramConsumerService.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/testservices/TestNetworkConsumerService.kt
Adds `getMetadata()` gRPC calls to Customer/Diagram/Network consumer clients. 
Relies on:
https://github.com/zepben/evolve-grpc/pull/80
Required for:
https://github.com/zepben/ewb-network-routes/pull/125
https://github.com/zepben/energy-workbench-server/pull/126
https://github.com/zepben/ewb-network-server/pull/58
Python sdk:
https://github.com/zepben/evolve-sdk-python/pull/135
If any of these are not applicable, strikethrough the line `~~like this~~`. **Do not delete it!**. Let the reviewer decide if you should have done it.
Please leave a summary of the breaking changes here. This is useful for the reviewer, but also is useful for communication to the team when merged (e.g. you could copy and paste the summary into slack).
> Ewb 3472 expose database metadata to clients

- changelog.md
- pom.xml
Use super pom version 0.34.1, fixing transient vulnerabilities from evolve-conn-jvm and test-utils.
- https://github.com/zepben/network-verifier-lib/pull/35
- https://github.com/zepben/ewb-network-routes/pull/127
- https://github.com/zepben/power-factory-exporter/pull/76
- https://github.com/zepben/opendss-exporter-jvm/pull/27
- https://github.com/zepben/hosting-capacity-service/pull/13
Updates Vert.x major version (3 -> 4).
> EWB-4098: Update super pom to 0.34.1

- .github/workflows/maven-lib-snapshot.yml
- .gitignore
Updating the snapshot workflow with product key and product repo for docs deployments
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
~- [ ] I have updated the changelog.~
> Updating the snapshot workflow with product key and product repo for docs deployments

- changelog.md
- src/main/kotlin/com/zepben/evolve/streaming/grpc/GrpcChannelBuilder.kt
- src/test/kotlin/com/zepben/evolve/streaming/grpc/GrpcChannelBuilderTest.kt
EE network hierarchy protobuf message is larger than the max gRPC default message size of 4mb. I've increased our channel builder to default to a max message size of 20mb, and made it configurable via the `build()` call.
Please leave a summary of the breaking changes here. This is useful for the reviewer, but also is useful for communication to the team when merged (e.g. you could copy and paste the summary into slack).
> Ewb 4287 set higher max protobuf message size

- changelog.md
- pom.xml
Updated evolve-grpc version to latest snapshot to make use of hosting capacity LoadShape protobuf support for reactive values.
Depends on: https://github.com/zepben/evolve-grpc/pull/91
It is a breaking change because the name for the values field changed to 'pValues', both the opendss-model-processor and the opendss-executor will need to be updated to handle this change.
> Updated evolve-grpc version to latest snapshot to make use of hosting capacity LoadShape protobuf support for reactive values.

- docs/docs/metrics.mdx
- src/main/kotlin/com/zepben/evolve/database/sqlite/metrics/tables/TableNetworkContainerMetrics.kt
- src/main/kotlin/com/zepben/evolve/metrics/NetworkContainer.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/metrics/MetricsSchemaTest.kt
- src/test/kotlin/com/zepben/evolve/metrics/NetworkContainerKtTest.kt
We want to be able to express metrics about both equipment containers and the areas of network they energize (e.g. equipment inside a substation vs all equipment powered by that substation). Therefore, we will make two additional network levels to express this.
- None
- https://github.com/zepben/network-verifier-lib/pull/41
No breaking changes.
> DEV-639: Add FeederTotal and SubstationTotal network levels

- pom.xml
Bump evolve-conn to use EntraID instead of Azure.
> Bump evolve-conn-jvm with EntraID rename

- changelog.md
- pom.xml
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/Conductor.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkCIMReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkCIMWriter.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/tables/TableCIMVersion.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/tables/iec61970/base/wires/TableConductors.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/UpgradeRunner.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/changesets/ChangeSet53.kt
- src/main/kotlin/com/zepben/evolve/services/network/NetworkServiceComparator.kt
- src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkCimToProto.kt
- src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkProtoToCim.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61970/base/wires/ConductorTest.kt
- src/test/kotlin/com/zepben/evolve/database/ResultSetExtensions.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/ChangeSetTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/changesets/customer/ChangeSet53CustomerValidator.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/changesets/diagram/ChangeSet53DiagramValidator.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/changesets/network/ChangeSet53NetworkValidator.kt
- src/test/kotlin/com/zepben/evolve/services/network/NetworkServiceComparatorTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/FillFields.kt
Added `designTemperature` and `designRating` to `Conductor` to support span level ratings based on how each conductor has been constructed for Essential Energy.
- https://github.com/zepben/ewb-grpc/pull/98
Only breaking change is the expected database schema upgrade
> DEV-550: Added `designTemperature` and `designRating` to `Conductor`

- changelog.md
- docs/docs/metrics.mdx
- src/main/kotlin/com/zepben/evolve/database/paths/EwbDataFilePaths.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/metrics/MetricsDatabaseWriter.kt
- src/main/kotlin/com/zepben/evolve/metrics/NetworkContainer.kt
- src/main/kotlin/com/zepben/evolve/metrics/NetworkContainerMetrics.kt
- src/main/kotlin/com/zepben/evolve/metrics/NetworkMetrics.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/metrics/MetricsDatabaseWriterTest.kt
- src/test/kotlin/com/zepben/evolve/metrics/NetworkContainerMetricsTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/CoreTraceTest.kt
See title. File is created in the folder specified in an additional constructor arg for `MetricsDatabaseWriter` (ideally one holding the network, customer, and diagram databases)
- None
- Use this feature in ingestors
To use this feature in an ingestor, edit the `MetricsDatabaseWriter` constructor to include the path of the model directory (most likely provided by a `EwbDataFilePaths` instance):
```
val ewbDataFilePaths = EwbDataFilePaths(Path.of("/path/to/ewb-data"))
val today = LocalDate.now()
val modelPath = ewbDataFilePaths.createDirectories(today)
val ingestionJob = IngestionJob(UUID.randomUUID())
// fill ingestion job with metrics...
val metricsDatabaseWriter = MetricsDatabaseWriter(
ewbDataFilePaths.metrics(),
ingestionJob,
modelPath …
```
> DEV-852: Create file named with job ID when saving metrics database

- changelog.md
- pom.xml
- src/main/kotlin/com/zepben/evolve/streaming/grpc/Connect.kt
- src/test/kotlin/com/zepben/evolve/streaming/grpc/ConnectTest.kt
* Update ewb-conn dependency
* Update Connect.connectWith... helper functions accordingly
* Rename `issuerDomain` to `issuer` in function parameters
* Update tests
Helper functions for creating authenticated connections to EWB have how changed signatures:
* `Connect.connectWithSecret`:
* `issuerDomain` has been renamed to `issuer`;
* `Connect.connectWithPassword`:
* `issuerDomain` has been renamed to `issuer`;
> Update to latest ewb-conn

- CONTRIBUTING.md
- changelog.md
- pom.xml
- src/main/kotlin/com/zepben/evolve/streaming/grpc/GrpcChannelBuilder.kt
- src/main/kotlin/com/zepben/evolve/streaming/grpc/GrpcConnectionException.kt
- src/main/kotlin/com/zepben/evolve/streaming/grpc/TokenCallCredentials.kt
- src/test/kotlin/com/zepben/evolve/streaming/grpc/GrpcChannelBuilderTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/grpc/TokenCallCredentialsTest.kt
Add connection tests for consumer connections. Moves verification of the connection to channel establishment rather than lazily.
Not breaking - but requires a version of EWB with `getMetadata`
> Add connection test

- changelog.md
- pom.xml
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/Switch.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkCimReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkCimWriter.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/tables/TableCimVersion.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/tables/iec61970/base/wires/TableSwitches.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/UpgradeRunner.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/changesets/ChangeSet56.kt
- src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkCimToProto.kt
- src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkProtoToCim.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/ChangeSetTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/changesets/network/ChangeSet56NetworkValidator.kt
- src/test/kotlin/com/zepben/evolve/services/network/NetworkServiceComparatorTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/FillFields.kt
Made the following changes:
* Changed `Switch.ratedCurrent` to a float to support milli-amp ratings of fuses.
* `SynchronousMachine.reactiveCapabilityCurveMRIDs` is now a list of strings. This is what it should have always been (missed in the PR review of the initial change).
* Added docstrings.
- https://github.com/zepben/ewb-grpc/pull/111
- https://github.com/zepben/ewb-network-routes/pull/149
- https://github.com/zepben/network-verifier-lib/pull/47
1. Update a database and make sure the sqlite file has updated the `rated_current` column of all switch tables to be a float, and your values are still there.
2. Request a `SynchronousMachine` via gRPC and ensure the curves collection is a list of mRID's rather than the curves themselves.
or 
rely on the extensive checks in the unit tests …
> [DEV-1534] `Switch.ratedCurrent` and `SynchronousMachine.reactiveCapabilityCurveMRIDs` fixes

- changelog.md
- docs/docs/datamodel.mdx
- docs/docs/phases.mdx
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/core/Terminal.kt
- src/main/kotlin/com/zepben/evolve/services/network/NetworkServiceComparator.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TerminalConnectivityConnected.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseSelector.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseStatus.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/RemovePhases.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/TracedPhases.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/TracedPhasesBitManipulation.kt
- src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkCimToProto.kt
- src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkProtoToCim.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61970/base/core/TerminalTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/NetworkServiceComparatorTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/FillFields.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/connectivity/TerminalConnectivityConnectedTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseSelectorTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseStatusTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/TracedPhasesBitManipulationTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/TracedPhasesTest.kt
When looking at setting/removing phases as part of a trace rework, we noticed 3 objects were being created for traced phases per terminal (`TracedPhases`, `normal: PhaseStatus`, `current: PhaseStatus`) and the `TracedPhases` was backed by a `UInt`. However, if we got rid of `TracedPhases` and just had `Terminal.normalPhases: PhaseStatus` and `Terminal.currentPhases: PhaseStatus` and backed `PhaseStatus` by a `UShort` we would only have 2 objects created to track phases, the same amount of memory to store the status (2 `UShort` vs 1 `UInt`) and less references being stored. 
If my calculations are right, this is about a 24-byte saving with compressed object pointers or a 48-byte saving without compressed object pointers (which we will have on very large networks with lots of terminals ➝ …
> DEV-1573 Traced phases optimisation

- changelog.md
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/BaseServiceReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/customer/CustomerDatabaseReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/customer/CustomerDatabaseWriter.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/diagram/DiagramDatabaseReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/diagram/DiagramDatabaseWriter.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/metadata/MetadataCollectionReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/metadata/MetadataCollectionWriter.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/metadata/MetadataEntryReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkDatabaseReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkDatabaseWriter.kt
- src/main/kotlin/com/zepben/evolve/services/Services.kt
- src/main/kotlin/com/zepben/evolve/services/common/BaseService.kt
- src/main/kotlin/com/zepben/evolve/services/customer/CustomerService.kt
- src/main/kotlin/com/zepben/evolve/services/diagram/DiagramService.kt
- src/main/kotlin/com/zepben/evolve/services/network/NetworkService.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/CimDatabaseSchemaTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/customer/CustomerDatabaseReaderTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/customer/CustomerDatabaseSchemaTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/diagram/DiagramDatabaseReaderTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/diagram/DiagramDatabaseSchemaTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkDatabaseReaderTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkDatabaseSchemaTest.kt
- src/test/kotlin/com/zepben/evolve/services/ServicesTest.kt
- src/test/kotlin/com/zepben/evolve/services/common/BaseServiceTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/stupid/StupidlyLargeNetwork.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/stupid/StupidlyLargeNetworkUtils.kt
* `BaseService` now contains a `MetadataCollection` to tightly couple the metadata to the associated service.
* Added `Services`, a new class which contains a copy of each `BaseService` supported by the SDK.
* Database readers and writes for each `BaseService` no longer accept a `MetadataCollection`, and will instead use the collection of the provided service.
* Database readers and writes for each `BaseService` no longer accept a `MetadataCollection`, and will instead use the collection of the provided service.
> [DEV-1775] Add `Services` collection and tightly coupled metadata to a service

- docs/docs/update-network-state-client.mdx
- src/main/kotlin/com/zepben/evolve/streaming/data/SetCurrentStatesStatus.kt
- src/main/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateService.kt
- src/test/kotlin/com/zepben/evolve/streaming/data/SetCurrentStatesStatusTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateServiceTest.kt
This is to allow the callback function of the update network state service to asynchronously accept request and respond by identifying each response with batch id.
Removed response object `UpdateNetworkStateClient.SetCurrentStatesResponse`.
None.
Test by using the `UpdateNetworkStateClient` and `UpdateNetworkStateService` classes.
Update to unreleased version of the code.
None
> [DEV-1857] Update JVM SDK - Update network state service

- docs/docs/update-network-state-service.mdx
- src/main/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateService.kt
- src/test/kotlin/com/zepben/evolve/streaming/data/SetCurrentStatesStatusTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateServiceTest.kt
Made the `UpdateNetworkStateService` handle processing of request asynchronously. The thread that handles the grpc request is blocked in `OnCompleted` until all processing are done via the `onSetCurrentStates` callback.
Minor fix in test src/test/kotlin/com/zepben/evolve/streaming/data/SetCurrentStatesStatusTest.kt
Updated docu and removed Java code example for `UpdateNetworkStateService` because we don't have interop implemented.
None.
Test by using the service interface.
Changes are related to unreleased version. No changelog update required.
No breaking change.
> [DEV-1865] Update jvm sdk update network state service to handle request processing asynchronously

- docs/docs/update-network-state-client.mdx
- pom.xml
- src/main/kotlin/com/zepben/evolve/streaming/data/CurrentStateEventBatch.kt
- src/main/kotlin/com/zepben/evolve/streaming/data/SetCurrentStatesStatus.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateClient.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateService.kt
- src/main/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateClient.kt
- src/test/kotlin/com/zepben/evolve/streaming/data/CurrentStateEventTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/data/SetCurrentStatesStatusTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateServiceTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/testservices/TestQueryNetworkStateService.kt
- src/test/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateClientTest.kt
- src/test/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateServiceTest.kt
Added new status messages to give clarity to how messages have been processed, and a new `rpc` to allowing sending statuses for backlog events.
blocked by:
* https://github.com/zepben/ewb-grpc/pull/122
blocking:
* https://github.com/zepben/ewb-network-routes/pull/169
* https://github.com/zepben/network-verifier-lib/pull/55
Nothing to test really, new functions will be built on this stuff.
~- [ ] I have updated the changelog.~
Breaking change only impacting yet to be released code.
> [DEV-2034] Updates for new network state responses.

- changelog.md
- src/main/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClient.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/NetworkConsumerClientTest.kt
Support `NetworkState` for `NetworkConsumerClient.getEquipmentContainer`.
None
N/A
- ~[ ] I have commented my code in any hard-to-understand or hacky areas.~
- ~[ ] I have updated any documentation required for these changes.~
Not a breaking change.
> [DEV-2209] Support NetworkState for getEquipmentContainer

- changelog.md
- pom.xml
- src/main/kotlin/com/zepben/evolve/services/network/NetworkServiceUtils.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToFeeders.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToLvFeeders.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/Util.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/operators/EquipmentContainerStateOperators.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/phases/RemovePhases.kt
- src/main/kotlin/com/zepben/evolve/testing/TestNetworkBuilder.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToFeedersTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToLvFeedersTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/DirectionConditionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/EquipmentStepLimitConditionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/EquipmentTypeStepLimitConditionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/OpenConditionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/PhaseValidator.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/phases/RemovePhasesTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/traversal/TraversalTest.kt
- src/test/kotlin/com/zepben/evolve/testing/TestNetworkBuilderTest.kt
* `RemovePhases` now stops at open points like the `SetPhases` counterpart, with major speed improvements. 
* When processing feeder assignments, all LV feeders belonging to a dist substation site will now be considered energized when the site is energized by a feeder. 
* You can now add sites to the `TestNetworkBuilder` via `addSite`. 
* You can now start the `AssignToFeeder` trace from a specified `Terminal` rather than all feeder heads.
> DEV-1983 assign feeders from terminals

- changelog.md
- docs/docs/update-network-state-client.mdx
- pom.xml
- src/main/kotlin/com/zepben/evolve/streaming/data/CurrentStateEvent.kt
- src/test/kotlin/com/zepben/evolve/streaming/data/CurrentStateEventTest.kt
Added support for add/remove of cut and jumper messages to the network state services for updating and querying network state events via gRPC.
None.
~- [ ] I have updated the changelog.~ Covered by initial message about network state services.
New sealed classes that may need to be handled, but nothing other than the branch this change is for is actually using them.
> Added support for add/remove of cut and jumper messages

- changelog.md
- pom.xml
- src/main/kotlin/com/zepben/evolve/streaming/data/CurrentStateEvent.kt
- src/main/kotlin/com/zepben/evolve/streaming/data/SetCurrentStatesStatus.kt
- src/main/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateService.kt
- src/main/kotlin/com/zepben/evolve/streaming/grpc/GrpcChannelBuilder.kt
- src/main/kotlin/com/zepben/evolve/streaming/mutations/UpdateNetworkStateService.kt
- src/test/kotlin/com/zepben/evolve/streaming/grpc/GrpcChannelBuilderTest.kt
I think this code works. PR TBA
Also added a timeout. Defaults to 5 seconds per request so a total time to fail of 5 seconds per service tested (currently three).
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
Please leave a summary of the breaking changes here. This …
> DEV-2143 Fix gRPC initial connection test in GrpcChannelBuilder

- changelog.md
- src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/Util.kt
- src/main/kotlin/com/zepben/evolve/testing/TestNetworkBuilder.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/UtilTest.kt
Fixes LvFeeders starting at open switches from being included when populating the normalEnergizedLvFeeders.
Run it with a problematic network
It's a fix
> Do not find LvFeeders starting with open switches in the Site

- changelog.md
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/AcLineSegment.kt
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/Clamp.kt
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/wires/Cut.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkCimReader.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTrace.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceQueueNext.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceStep.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceStepPathProvider.kt
- src/main/kotlin/com/zepben/evolve/testing/TestNetworkBuilder.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/stupid/StupidlyLargeNetwork.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceQueueNextTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceStepPathProviderTest.kt
- src/test/kotlin/com/zepben/evolve/testing/TestNetworkBuilderTest.kt
Added support for `Cut` and `Clamp` on `AcLineSegment` in the tracing API.
None.
Create a network model that includes cuts and clamps on an AcLineSegment. Run a trace over it and see cuts and clamps are included when stepping along the network.
The unit tests also hopefully give confidence that it works.
~- [ ] I have updated any documentation required for these changes.~ 
AcLineSegments can now only have 2 terminals. Segments with mid-span terminals need to be migrated to use clamps.
> DEV-2316 Support cuts and clamps in tracing

- changelog.md
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTrace.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/Conditions.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/NetworkTraceQueueCondition.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/NetworkTraceStopCondition.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/OpenCondition.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/traversal/Traversal.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/CutsAndClampsNetwork.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/SetDirectionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceStepPathProviderTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/conditions/DirectionConditionTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/traversal/TraversalTest.kt
The follow fixes were added to Traversal and NetworkTrace:
* `canStopAtStartItem` now works for branching traversals.
* Traversal start items are added to the queue before traversal starts, so that the start items honour the queue type order.
* Stop conditions on the `NetworkTrace` now are checked based on a step type, like `QueueCondition` does, rather than by checking `canActionItem`.
* Cuts and Clamps are now supported in `SetDirection` and `DirectionCondition`.
* `NetworkTrace` now handles starting on `Cut `, `Clamp`, and `AcLineSegment` and their terminals in a explicit / sensible way.
* `NetworkTracePathProvider` now correctly handles next paths when starting on a `Clamp` terminal.
* https://app.clickup.com/t/6929263/DEV-2500
Unit tests have been added.
If any of these are not …
> DEV-2568 Tracing fixes and more unit tests

- changelog.md
- pom.xml
- src/main/kotlin/com/zepben/evolve/services/network/tracing/traversal/Traversal.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/networktrace/NetworkTraceTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/traversal/TraversalTest.kt
Bugfix for change introduced in v0.26.0
- Routes
- Verifier Lib
Unit tests.
Non-breaking
> `NetworkTrace`/`Traversal` now correctly respects `canStopOStart` when providing multiple start items.

- changelog.md
- pom.xml
- src/main/kotlin/com/zepben/evolve/cim/iec61968/assets/Asset.kt
- src/main/kotlin/com/zepben/evolve/cim/iec61970/base/core/PowerSystemResource.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkCimReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkCimWriter.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkDatabaseTables.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/network/NetworkServiceReader.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/tables/TableCimVersion.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/tables/associations/TableAssetsPowerSystemResources.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/UpgradeRunner.kt
- src/main/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/changesets/ChangeSet59.kt
- src/main/kotlin/com/zepben/evolve/services/common/ReferenceResolvers.kt
- src/main/kotlin/com/zepben/evolve/services/common/Resolvers.kt
- src/main/kotlin/com/zepben/evolve/services/network/NetworkServiceComparator.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToFeeders.kt
- src/main/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToLvFeeders.kt
- src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkCimToProto.kt
- src/main/kotlin/com/zepben/evolve/services/network/translator/NetworkProtoToCim.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61968/assets/AssetTest.kt
- src/test/kotlin/com/zepben/evolve/cim/iec61970/base/core/PowerSystemResourceTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/ChangeSetTest.kt
- src/test/kotlin/com/zepben/evolve/database/sqlite/cim/upgrade/changesets/network/ChangeSet59NetworkValidator.kt
- src/test/kotlin/com/zepben/evolve/services/network/testdata/FillFields.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToFeedersTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/tracing/feeder/AssignToLvFeedersTest.kt
- src/test/kotlin/com/zepben/evolve/services/network/translator/NetworkTranslatorTest.kt
As per title - pretty straightforward, however have also included an update to evolve-conn which fixes some server side auth issues.
And have included a fix to AssignTo[Lv]Feeders to assign PowerElectronicUnits to the feeder as well.
Depends on:
- https://github.com/zepben/ewb-grpc/pull/128
Once EWB PR is done you can try link a Pole to a conductor in an ingestor, build a model, and see if you can retrieve that relationship through the NetworkConsumerClient.
Or you can just run the tests and pray.
Not breaking - I think should maintain compatibility with older versions of EWB
> Add Asset to PowerSystemResource relationship

- changelog.md
- src/main/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateService.kt
- src/test/kotlin/com/zepben/evolve/streaming/get/QueryNetworkStateServiceTest.kt
`QueryNetworkStateService.reportBatchStatus` now correctly sends the `Empty` response.
List any other tasks / PRs that are required to be merged alongside this one (e.g. front end task for back end change or vice versa). If a PR exists, add a link. If not, just add an appropriate note here so reviewers know there is a dependency and will hold off merging until all things are ready.
Explain in detail how your reviewer can test the changes proposed in this PR. If it cannot be tested, leave an explanation on why.
Not a breaking change
> Fix  QueryNetworkStateService.reportBatchStatus oncomplete

- changelog.md
- src/main/kotlin/com/zepben/ewb/database/postgres/metrics/MetricsEntryWriter.kt
- src/test/kotlin/com/zepben/ewb/database/postgres/metrics/MetricsWriterTest.kt
The Ops teams was having issues with the gis-network-extractor because it would fail with a null pointer exception when processing metrics job sources with null timestamps. 
The schema supports a null timestamp and we have customers with metrics data that have a null timestamp so it should support handling a null timestamp.
NONE
Try to process a job source that has a null timestamp in its metadata. It will work now, it did not before this fix.
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~ nothing hacky about the fix
When developing applications, use following guidelines for information security considerations:
* …
> Fixed bug that would cause a null pointer exception when processing metrics job sources with a null metadata timestamp

- changelog.md
- pom.xml
Update evolve-grpc from 0.36.0 to 1.0.0 to support customer level load results in HCS.
There were no changes in 0.37.0.
- https://github.com/zepben/ewb-grpc/pull/131
Next down the chain:
- https://github.com/zepben/network-verifier-lib/pull/72
No relevance to this code.
Only dependency updates. It is a GRPC change so everything should be using matching versions regardless.
> DEV-3252 Update grpc version to support customer level load
